### ISSUE TITLE
Ambigious data

### ISSUE THREAD

**Issue by ujjvalksharma** [open-numbers/ddf--open_numbers--covid_government_response#1]
What is the meaning of **geo** and **time** in data sets? How are they related to real world. Like how to know the country from geo and total days from time?

**Comment by semio** [comment]
Hi! This dataset is harmonized to the Open Numbers name space, in which **geo** stands for "Geographic location". You can find all geo entities from csv files `ddf--entities--geo*.csv` in the dataset (for example all countries are listed in `ddf--entities--geo--country.csv`). You can also find the meanings of column names from `ddf--concepts.csv` file.

If you are not familiar with entity domain/entity set and other DDF model concepts, it's recommanded to read the [the introduction to DDF](https://open-numbers.github.io/ddf.html) and [DDFcsv format document](https://docs.google.com/document/d/1aynARjsrSgOKsO1dEqboTqANRD1O9u7J_xmxy8m5jW8).

for the **time** column, it's date string in "YYYYMMDD" format (20210323 for today). We found that there is an issue in our pipeline so the time values were not correct. I fixed the issue and updated the dataset. Please check the latest dataset and feel free to let us know if you have other questions :)
